name:                cursetweet
version:             0.1.0.0
github:              "githubuser/cursetweet"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2021 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/cursetweet#readme>

default-extensions:
  - AllowAmbiguousTypes
  - RankNTypes
  - UnicodeSyntax
  - ScopedTypeVariables
  - StandaloneDeriving
  - EmptyDataDecls
  - FlexibleContexts
  - FlexibleInstances
  - FunctionalDependencies
  - KindSignatures
  - TypeOperators
  - MultiParamTypeClasses
  - PartialTypeSignatures
  - DuplicateRecordFields
  - TupleSections
  - TypeFamilies
  - OverloadedLabels
  - OverloadedStrings
  - DeriveFunctor
  - DeriveGeneric
  - NoImplicitPrelude
  - DataKinds
  - ConstraintKinds
  - UndecidableInstances
  - InstanceSigs
  - Strict
  - PatternSynonyms
  - BlockArguments
  - LambdaCase
  - EmptyDataDeriving
  - TypeOperators
  - ViewPatterns
  - EmptyCase
  - PolyKinds
  - GeneralizedNewtypeDeriving
  - DerivingStrategies

ghc-options:
  - -Wno-partial-type-signatures -Wincomplete-patterns -Wincomplete-uni-patterns
  - -Wno-deprecations -Wall -Wcompat -Wincomplete-record-updates
  - -Wincomplete-uni-patterns -Wredundant-constraints 
  - -Werror
  - -fplugin=RecordDotPreprocessor

dependencies:
- base >= 4.7 && < 5
- bytestring
- containers
- record-dot-preprocessor
- record-hasfield
- tasty
- tasty-hunit
- tasty-discover
- text

library:
  source-dirs: src

executables:
  cursetweet:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cursetweet

tests:
  cursetweet-test:
    main:                Main.hs
    source-dirs:         
      - src
    other-modules:
      - Lib
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
